name: Dailve
options:
  bundleIdPrefix: com.dailve
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"

targets:
  Dailve:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Data
      - path: Domain
      - path: Presentation
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/Dailve.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.dailve.health
        PRODUCT_NAME: Dailve
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_NSHealthShareUsageDescription: "Dailve needs access to your health data to calculate condition scores and track your fitness progress."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "Dailve may write workout and body composition data to Health."
    entitlements:
      path: Resources/Dailve.entitlements
    dependencies:
      - sdk: HealthKit.framework

  DailveTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ../DailveTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dailve.health.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Dailve.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Dailve"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Dailve

  DailveUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ../DailveUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dailve.health.uitests
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: Dailve
    dependencies:
      - target: Dailve
