name: Dailve
options:
  bundleIdPrefix: com.raftel
  deploymentTarget:
    iOS: "26.0"
    watchOS: "26.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    DEVELOPMENT_TEAM: "4GWU9QB2JZ"
    CODE_SIGN_IDENTITY: "iPhone Developer"

schemes:
  Dailve:
    build:
      targets:
        Dailve: all
        DailveWatch: all
        DailveTests: [test]
        DailveUITests: [test]
    test:
      targets:
        - DailveTests
        - DailveUITests

  DailveTests:
    build:
      targets:
        Dailve: all
        DailveTests: [test]
    test:
      targets:
        - DailveTests

  DailveWatch:
    build:
      targets:
        DailveWatch: all

targets:
  Dailve:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Data
      - path: Domain
      - path: Presentation
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/Dailve.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.raftel.dailve
        PRODUCT_NAME: Dailve
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.1.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSHealthShareUsageDescription: "Dailve needs access to your health data to calculate condition scores and track your fitness progress."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "Dailve may write workout and body composition data to Health."
    entitlements:
      path: Resources/Dailve.entitlements
      properties:
        aps-environment: development
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.raftel.dailve
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: "$(TeamIdentifierPrefix)$(CFBundleIdentifier)"
    dependencies:
      - sdk: HealthKit.framework
      - target: DailveWatch
        embed: true

  DailveWatch:
    type: application
    platform: watchOS
    sources:
      - path: ../DailveWatch
        excludes:
          - "Resources/**"
      - path: ../DailveWatch/Resources
      # Shared SwiftData models
      - path: Data/Persistence/Models
        group: Shared/Models
      - path: Data/Persistence/Migration
        group: Shared/Migration
      # Shared Domain enums (required by @Model files)
      - path: Domain/Models/ExerciseCategory.swift
        group: Shared/Domain
      - path: Domain/Models/MuscleGroup.swift
        group: Shared/Domain
      - path: Domain/Models/Equipment.swift
        group: Shared/Domain
      - path: Domain/Models/ExerciseDefinition.swift
        group: Shared/Domain
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raftel.dailve.watchkitapp
        PRODUCT_NAME: DailveWatch
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.1.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        WATCHOS_DEPLOYMENT_TARGET: "26.0"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        DEVELOPMENT_TEAM: "4GWU9QB2JZ"
        CODE_SIGN_IDENTITY: "Apple Development"
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.raftel.dailve
        INFOPLIST_KEY_NSHealthShareUsageDescription: "Dailve needs access to your health data to track heart rate during workouts."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "Dailve records your workout data to Health."
        CODE_SIGN_ENTITLEMENTS: ../DailveWatch/DailveWatch.entitlements
    entitlements:
      path: ../DailveWatch/DailveWatch.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.raftel.dailve
        com.apple.developer.icloud-services:
          - CloudKit
    dependencies:
      - sdk: HealthKit.framework
      - sdk: WatchConnectivity.framework

  DailveTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ../DailveTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raftel.dailve.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Dailve.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Dailve"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Dailve

  DailveUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ../DailveUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raftel.dailve.uitests
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: Dailve
    dependencies:
      - target: Dailve
